apiVersion: v1
kind: Secret
metadata:
  name: kasten-frs-web-helper-credentials
  namespace: kasten-io
type: Opaque
stringData:
  HELPER_USERNAME: "admin"
  # Generate with: openssl rand -base64 32
  HELPER_PASSWORD: "REPLACE_ME"
  HELPER_COOKIE_SECRET: "REPLACE_ME_32_BYTES_MIN"
